language: node_js
node_js:
  - 0.8

before_script: 
- npm install
- sudo npm install -g coffee-script
- wget https://github.com/n1k0/casperjs/archive/1.0.0-RC4.tar.gz -O - | tar zxv
- sudo ln -s `pwd`/casperjs-1.0.0-RC4/bin/casperjs /usr/local/bin/casperjs
- which phantomjs
- which casperjs
- "echo $PATH"

script: cake test

