language: node_js
node_js:
  - 0.8

before_script: 
- npm install
- sudo npm install -g coffee-script
- wget https://github.com/n1k0/casperjs/archive/1.0.0-RC4.tar.gz -O - | tar xv
- sudo ln -s casperjs-1.0.0-RC4/bin/casperjs /usr/local/bin/casperjs

script: cake test

